# Generated by Django 4.2.4 on 2023-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_orderiitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderIitem',
            new_name='OrderItem',
        ),
    ]
