# Generated by Django 4.2.4 on 2023-08-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_customer_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='market.item'),
        ),
    ]
