# Generated by Django 4.2.4 on 2023-08-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_orderitem_item_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
