# Generated by Django 4.2.4 on 2023-08-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
