# Generated by Django 4.2.4 on 2023-09-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_cart_remove_orderitem_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='market.item'),
        ),
    ]
