# Generated by Django 4.2.4 on 2023-09-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_cart_item_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
